version: "3"
services:
  db:
    image: postgres:9.5
    volumes:
      - postgresql:/var/lib/postgresql/data
  backend:
    build: ./backend
    expose:
      - '8000'
    links:
      - db
    env_file:
      - .env
  webserver:
    build: ./webserver
    ports:
      - 80:80
      - 443:443
    environment:
      FQDN: localhost
      DEBUG: 1
    volumes:
      - ./webserver/ssl:/ssl
      - ./webserver:/webserver
volumes:
  postgresql:
  www:
  profiles: