name: containers-publish
on:
  workflow_run:
    workflows:
      - "containers-test"
    branches:
      - main
    types:
      - completed
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: deploy containers
        run: |
          cd containers
          ./deploy
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
