name: containers-test
on:
  push:
    branches:
      - main
    paths:
      - "containers/**"
      - "packages/lesspass-site/**"
  pull_request:
    paths:
      - "containers/**"
      - "packages/lesspass-site/**"
jobs:
  test-backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: |
          cd containers/backend
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python manage.py test
  test-site:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn workspace lesspass-site test
  test-integration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd containers
          ./test
