name: lesspass-entropy-test
on:
  push:
    branches:
      - main
    paths:
      - "packages/lesspass-entropy/**"
  pull_request:
    paths:
      - "packages/lesspass-entropy/**"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn workspace lesspass-crypto build
      - run: yarn workspace lesspass-entropy test
