name: lesspass-publish
on:
  workflow_run:
    workflows:
      - "lesspass-test"
    branches:
      - main
    types:
      - completed
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: |
          cd packages/lesspass
          yarn publish --non-interactive
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
