name: mobile-test
on:
  push:
    branches:
      - main
    paths:
      - "mobile/**"
  pull_request:
    paths:
      - "mobile/**"
jobs:
  test-mobile:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: |
          cd mobile
          yarn install
          yarn test